//created on: Dec 15, 2017
package symptomsBased
import com.ajitrisantoso.ItemSymptoms;
import com.ajitrisantoso.ItemRS;
import com.ajitrisantoso.Hope;

rule "TraumaAndBleeding"
	when
        //conditions
        $item : ItemSymptoms (typeofSymptoms == ItemSymptoms.Symptoms.TraumaAndBleeding)
         exists( ItemRS ( available == true ) )
        itemRS : ItemRS( DrSpBedahTulang == "ADA" && OR ==1 && kamarInap == 1) 
    then
        //actions
        System.out.println( "Terdapat Rumah Sakit Sesuai Dengan Kondisi Pasien :  " + itemRS.getNamaRS() );
        $item.setExpertRec("Terdekat, Dokter Spesialist Bedah Tulang,Kamar Operasi,Kamar Inap Tersedia");
end

